### ISSUE TITLE
Jimmi does not consider custom URLs

### ISSUE THREAD

**Issue by ndren** [Music-Bot-for-Jitsi/Jimmi#145] opened 2022-07-31 16:49 UTC
### Description
When using a custom invidious instance URL Jimmi keeps using invidious.snopyta.org.

### Steps to reproduce:
Run !play https://yewtu.be/watch?v=dQw4w9WgXcQ

### What was supposed to happen?
It should use this yewtu.be, rather than invidious.snopyta.org. This is important right now because invidious.snopyta.org is down: https://github.com/iv-org/invidious/issues/3231

### Further information:
Firefox 103 on Linux, using the default instance jimmi.xyz

Thanks!

**Comment by p-fruck** [comment] 2022-07-31 21:35
Thanks for reporting the issue! Unfortunately, the problem is a little different than you might expect. Jimmi has no logic to parse the URL and fetch videos from the given instance, instead he passes the whole URL to an invidious instance defined beforehand. Taking a look at the [invidious api list](https://api.invidious.io/) you can see that yewtube doesn't provide API access. Jimmi should automatically select the highest ranked instance that has public API access enabled. At the time of writing the [vid.puffyan.us](https://vid.puffyan.us/) instance is ranked the highest, but this instance has signup enabled. I am not quite sure if signup requires API authentication for simple video fetching or only for specific endpoints. Could you try to restart Jimmi and check if the issue still persists?

If you require a quick and dirty hack to enforce a given instance, you can define your own JSON file as follows:
```json
[[
  "My Instance",
  {
    "type": "https",
    "api": "true",
    "uri": "https://example.com"
  }
]]
```

This file has to be hosted somewhere (you can simply create a GitHub gist if you like). Now you can set Jimmis `INVIDIOUS_INSTANCELIST_URL` variable to your JSON file URL. Make sure to replace `example.com` with an instance that has API access enabled and doesn't require signup!

Please let me know if this helped you

**Comment by ndren** [comment] 2022-08-01 11:41
Hi!

Sorry if this was not too clear, I am using the public instance jimmi.xyz.

One thing that seems to happen is that jimmi.xyz is still using invidious.snopyta.org, even though it was downranked a lot on api.invidious.io. It does not seem to try and query api.invidious.io, rather it instead sticks to the one defined in the minified JavaScript index*.js file. I will try to host my own instance.

**Comment by ndren** [comment] 2022-08-01 12:04
I am running into the following when running jimmi-x86_64-unknown-linux-gnu:
```
Using chrome on remote endpoint!
Could not create browser!
ErrorEvent {
  bubbles: false,
  cancelable: false,
  composed: false,
  currentTarget: null,
  defaultPrevented: false,
  eventPhase: 0,
  srcElement: null,
  target: WebSocket {
    [Symbol()]: {
      assignedSlot: false,
      hasActivationBehavior: false,
      host: null,
      listeners: { open: [Array], error: [Array] },
      mode: ""
    },
    [Symbol("[[rid]]")]: undefined,
    [Symbol("[[readyState]]")]: 3,
    [Symbol("[[extensions]]")]: "",
    [Symbol("[[protocol]]")]: "",
    [Symbol("[[url]]")]: "ws://browserlessservice:3000/",
    [Symbol("[[binaryType]]")]: "blob",
    [Symbol("[[bufferedAmount]]")]: 0,
    [Symbol("[[webidl.brand]]")]: Symbol("[[webidl.brand]]")
  },
  returnValue: true,
  timeStamp: 1659354082999,
  type: "error",
  message: "Error: failed to lookup address information: Name or service not known",
  filename: "",
  lineno: 0,
  colno: 0,
  error: Error: failed to lookup address information: Name or service not known
}
```
It seemed to run when removing BROWSER_WS_ENDPOINT option from .env, though after that it gives a 502 response to any URL I try to queue. 
I am using the released binaries. I have chromium installed (though I am a bit disappointed it seems to break under firefox even with BROWSER_WS_ENDPOINT removed: 
```
Could not create browser!
Error: Failed to launch the browser process!
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at waitForWSEndpoint (https://deno.land/x/puppeteer@9.0.2/src/deno/BrowserRunner.ts:140:11)
    at async BrowserRunner.setupConnection (https://deno.land/x/puppeteer@9.0.2/src/deno/BrowserRunner.ts:122:35)
    at async ChromeLauncher.launch (https://deno.land/x/puppeteer@9.0.2/src/deno/Launcher.ts:67:32)
    at async initializeBrowser (file:///home/runner/work/Jimmi/Jimmi/backend/src/service/Jimmi.service.ts:37:24)
    at async file:///home/runner/work/Jimmi/Jimmi/backend/src/service/Jimmi.service.ts:15:17
```
)

**Comment by p-fruck** [comment] 2022-08-01 12:23
Ah I overlooked that you are using the web version. This is actually our v1 release. You are currently trying to setup our v2 POC release (very confusing, I know). The V2 was a POC release I am looking forward to drop. The code that you are likely interested in is currently located [here](https://github.com/Music-Bot-for-Jitsi/Jimmi/tree/v1.0.0).

I adjusted the URL manually and changed the invidious instance to [vid.puffyan.us](https://vid.puffyan.us/). I hope this works.

If you still want to host you own instance however, you also need to modify the browser extension and change https://jimmi.xyz in browser/manifest.json and browser/rules.json to your own domain. The invidious url can be changed in `Jimmi/frontend/src/plugins/MusicPlugin.ts`

Sorry for the inconvenience, I am looking forward to cleanup this project in September, but currently I do not have the time to do so.

**Comment by ndren** [comment] 2022-08-01 13:20
Hi! I got hit by CORS policy on googlevideo.com, which I have solved with CORS Unblock. How practical would it be to allow *googlevideo.com*? (Alternatively, choosing an instance that defaults to proxying video like inv.riverside.rocks might be easier.)

Thanks very much!

**Comment by ndren** [comment] 2022-08-01 13:30
Actually, I might be wrong on that since it seems the API does not seem to respect those frontend settings...

**Comment by p-fruck** [comment] 2022-08-01 13:33
I suppose you don't have our browser extension installed as described in the [getting started guide](https://github.com/Music-Bot-for-Jitsi/Jimmi/tree/v1.0.0#rocket-get-started)? The browser extensions circumvents this very problem. The problem with proxying content from Youtube is
1. I am not quite sure how legal this is
2. You need the bandwith to proxy all the concurrent traffic from all your users. I guess this is the reason why the riverside instance is so slow.

The Jimmi extension does exactly the same as the CORS Unblock extension, but in a safer, more restricted and declarative way.

> Actually, I might be wrong on that since it seems the API does not seem to respect those frontend settings...

Can you go a little more into detail? :)

**Comment by ndren** [comment] 2022-08-01 16:10
I can't use that extension, I'm running on Firefox.

> Can you go a little more into detail? :)
https://inv.riverside.rocks/api/v1/videos/dQw4w9WgXcQ does not consider that the global settings on the instance enable proxied video, and therefore just returns googlevideo.com for audio/mp4. Further, if I append ?local=true it still returns the same thing, so I am not sure if this use case is actually supported by invidious in the first place or if I am not finding the right documentation for the API itself rather than the frontend parameters (on which appending &local=true works fine).

Not a lawyer, but I don't see why proxying videos specifically should be any more an issue compared

**Comment by SamantazFox** [comment] 2022-08-01 16:24
> Actually, I might be wrong on that since it seems the API does not seem to respect those frontend settings...

Yes, this is a bug. See https://github.com/iv-org/invidious/issues/3221

**Comment by p-fruck** [comment] 2022-08-02 11:12
Now that `local=true` seems pretty interesting, I will definitely keep an eye on that.

> I can't use that extension, I'm running on Firefox.

I'm aware, I also prefer Firefox over Chrome. Mozilla plans to support the MV3 and thereby `declarativeNetRequest` (which the extension is built on) until [the end of this year](https://blog.mozilla.org/addons/2022/05/18/manifest-v3-in-firefox-recap-next-steps/). I will not waste time implementing legacy code just to support Firefox because the Mozilla guys lack behind. If you don't want to use Chromium you can also use your CORS Unblock extension until Firefox officially supports  declarative net requests

**Comment by p-fruck** [comment] 2022-08-10 20:05
Closing this as completed. Dynamically changing the Invidious URL however is on the ToDo list ;)

**Closed by p-fruck** 2022-08-10 20:05 UTC
Labels: bug, help wanted, needs assignee
